CREATE DATABASE IF NOT EXISTS siscoe;

USE siscoe;

CREATE TABLE IF NOT EXISTS usuario(
	mat INTEGER UNSIGNED NOT NULL,	
	nome VARCHAR(255) NOT NULL, 
	senha CHAR(32) NOT NULL,
	email VARCHAR(255) NOT NULL,
	tel VARCHAR(11) NOT NULL,
	cargo VARCHAR(16) NOT NULL,  	
	dtNasc DATE NOT NULL,
	dtIng DATE NOT NULL, 
	foto VARCHAR(1024), 
	PRIMARY KEY (mat)
);

CREATE TABLE IF NOT EXISTS peca(
	num INTEGER(7) UNSIGNED NOT NULL,
	tipo VARCHAR(16) NOT NULL,
	modelo VARCHAR(255) NOT NULL,
	fornecedor VARCHAR(255) NOT NULL,
	dtFab DATE NOT NULL,
	garantia VARCHAR(255) NOT NULL,
	obs TEXT,
	PRIMARY KEY (num)
);

CREATE TABLE IF NOT EXISTS pedido(
	id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT, 
	tipo VARCHAR(16) NOT NULL,
	qtd INTEGER UNSIGNED NOT NULL,
	obs TEXT,
	PRIMARY KEY (id)
);
